### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by shadowTW** [0xSSOMPW/aniscraper#12]
uhm hi, I have a issue, the url link from streamtape doesn't work
https://signed.bio/v2/episode_stream?episode=death-note-60?ep=1464&episode_type=Dub&server=Streamtape
u can try it here

**Comment by shadowTW** [comment]
![image](https://github.com/user-attachments/assets/06374743-80eb-40f9-92c5-027bbc2e5ea5)

**Comment by falcon71181** [comment]
@shadowTW 
api res is
```
{"StreamTape":{"url":"https://streamtape.com/get_video?id=oWyWajorQ9FW6M&expires=1730007581&ip=F0uRKRSUFI9XKxR&token=H8HLQPtx6Vv3","is_m3u8":false}}
```

here url is complete including token , if you use complete url it will work ,
in case u r trying to just use `https://streamtape.com/get_video?id=oWyWajorQ9FW6M` it will fail as short url will be in string format - `https://streamtape.com/e/oWyWajorQ9FW6M`


U can format url from api res  for now.

### I will add minimal url in next update of this lib.

**Comment by falcon71181** [comment]
### Full url `https://streamtape.com/get_video?id=oWyWajorQ9FW6M&expires=1730008061&ip=F0uRKRSUFI9XKxR&token=w-3v770kDt62`
<img width="1470" alt="Screenshot 2024-10-26 at 3 49 56 PM" src="https://github.com/user-attachments/assets/7c99d0d8-76fa-403b-8f52-dc7b8ecb0281">


### Short url `https://streamtape.com/e/oWyWajorQ9FW6M`
<img width="1470" alt="Screenshot 2024-10-26 at 3 47 41 PM" src="https://github.com/user-attachments/assets/8f4822c9-0410-4563-8deb-cc95e6598955">
